import React from 'react';

export const visit = <span role="img" aria-label="emoji"> 🎉💯</span>;
export const count = <span role="img" aria-label="emoji"> 🤩🥳</span>;
export const top = <span role="img" aria-label="emoji">👆🏻</span>;
export const contactPage = <span role="img" aria-label="emoji">📬</span>;
export const projectsPage = <span role="img" aria-label="emoji">👩🏻‍💻</span>;
export const aboutPage = <span role="img" aria-label="emoji">👋🏻</span>;
export const about = <span role="img" aria-label="emoji">😎</span>;
export const education = <span role="img" aria-label="emoji">🎓</span>;
export const date = <span role="img" aria-label="emoji">📆</span>;
export const location = <span role="img" aria-label="emoji">🏫</span>;
export const link = <span role="img" aria-label="emoji">🔗</span>;
export const honours = <span role="img" aria-label="emoji">🥇</span>;
export const experience = <span role="img" aria-label="emoji">💼</span>;
export const role = <span role="img" aria-label="emoji">🌱</span>;
export const publication = <span role="img" aria-label="emoji">📖</span>;
export const interest = <span role="img" aria-label="emoji">🤩</span>;
export const check = <span role="img" aria-label="emoji">✅</span>;
export const skills = <span role="img" aria-label="emoji">🌟</span>;